name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Repack package
      run: |
          cd package
          zip -9yr ../kernel-package_android-x86.zip *

    - uses: actions/upload-artifact@v1
      with:
        name: Kernel Package
        path: kernel-package_android-x86.zip

    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "${{ env.GITHUB_SHA }}"
        files: |
            kernel-package_android-x86.zip